apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm-order
  template:
    metadata:
      labels:
        app: ecomm-order
    spec:
      containers:
      - name: order
        image: wajvi/ecomm-order:latest
        ports:
        - containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm-order
spec:
  type: ClusterIP
  selector:
    app: ecomm-order
  ports:
  - name: http
    port: 80
    targetPort: 8084
