apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm-product
  template:
    metadata:
      labels:
        app: ecomm-product
    spec:
      containers:
      - name: product
        image: wajvi/ecomm-product:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm-product
spec:
  type: ClusterIP
  selector:
    app: ecomm-product
  ports:
  - name: http
    port: 80
    targetPort: 8080
